apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: java-function1
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: java-function1
spec:
  source:
    git:
      url: https://github.com/tfynes-pivotal/java-function1
      ref:
        branch: main
  build:
    env:
      - name: BP_FUNCTION
        value: functions.Handler